name: doorgym1
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2019.5.15=1
  - certifi=2019.6.16=py37_1
  - cffi=1.12.3=py37h2e261b9_0
  - cudatoolkit=10.0.130=0
  - freetype=2.9.1=h8a8886c_1
  - intel-openmp=2019.4=243
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - mkl=2019.4=243
  - mkl-service=2.0.2=py37h7b6447c_0
  - mkl_fft=1.0.14=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.16.4=py37h7e9f1db_0
  - numpy-base=1.16.4=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openssl=1.1.1c=h7b6447c_1
  - pillow=6.1.0=py37h34e0f95_0
  - pip=19.2.2=py37_0
  - pycparser=2.19=py37_0
  - python=3.7.4=h265db76_1
  - pytorch=1.2.0=py3.7_cuda10.0.130_cudnn7.6.2_0
  - readline=7.0=h7b6447c_5
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_0
  - sqlite=3.29.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.4.0=py37_cu100
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.8.0
    - alabaster==0.7.12
    - astor==0.8.0
    - atari-py==0.2.6
    - atomicwrites==1.3.0
    - attrs==19.1.0
    - babel==2.7.0
    - backcall==0.1.0
    - chardet==3.0.4
    - click==7.0
    - cloudpickle==1.2.1
    - cycler==0.10.0
    - cython==0.29.13
    - decorator==4.4.0
    - dill==0.3.0
    - docutils==0.15.2
    - future==0.17.1
    - gast==0.2.2
    - glfw==1.8.3
    - google-pasta==0.1.7
    - grpcio==1.23.0
    - gtimer==1.0.0b5
    - gym==0.14.0
    - h5py==2.9.0
    - idna==2.8
    - imagehash==4.0
    - imageio==2.5.0
    - imagesize==1.1.0
    - importlib-metadata==0.20
    - ipdb==0.12.2
    - ipython==7.8.0
    - ipython-genutils==0.2.0
    - jedi==0.15.1
    - jinja2==2.10.1
    - joblib==0.13.2
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - kiwisolver==1.1.0
    - lockfile==0.12.2
    - markdown==3.1.1
    - markupsafe==1.1.1
    - matplotlib==3.1.1
    - more-itertools==7.2.0
    - mpi4py==3.0.2
    - mujoco-py==2.0.2.5
    - numpydoc==0.9.1
    - opencv-python==4.1.1.26
    - packaging==19.1
    - parso==0.5.1
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - pluggy==0.12.0
    - progressbar2==3.43.1
    - prompt-toolkit==2.0.9
    - protobuf==3.9.1
    - ptyprocess==0.6.0
    - py==1.8.0
    - pyglet==1.3.2
    - pygments==2.4.2
    - pyparsing==2.4.2
    - pytest==5.1.2
    - pytest-instafail==0.3.0
    - python-dateutil==2.8.0
    - python-utils==2.3.0
    - pytz==2019.2
    - pywavelets==1.0.3
    - pyzmq==18.1.0
    - requests==2.22.0
    - scipy==1.3.1
    - snowballstemmer==1.9.0
    - sphinx==2.2.0
    - sphinx-rtd-theme==0.4.3
    - sphinxcontrib-applehelp==1.0.1
    - sphinxcontrib-devhelp==1.0.1
    - sphinxcontrib-htmlhelp==1.0.2
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.2
    - sphinxcontrib-serializinghtml==1.1.3
    - tensorboard==1.14.0
    - tensorboardx==1.8
    - tensorflow==1.14.0
    - tensorflow-estimator==1.14.0
    - termcolor==1.1.0
    - tqdm==4.35.0
    - traitlets==4.3.2
    - urllib3==1.25.3
    - wcwidth==0.1.7
    - werkzeug==0.15.6
    - wrapt==1.11.2
    - zipp==0.6.0
    - zmq==0.0.0
prefix: /home/demo/miniconda3/envs/doorgym1

